// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpxYa6MRQbmNY-Qai1TulAbZaTDNEY22Y',
    appId: '1:218095244490:web:4035afa86c68269bc31033',
    messagingSenderId: '218095244490',
    projectId: 'recommendation-app-3c6d6',
    authDomain: 'recommendation-app-3c6d6.firebaseapp.com',
    storageBucket: 'recommendation-app-3c6d6.firebasestorage.app',
    measurementId: 'G-9VDLP529ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLvFoh_OIfcSRzYY_n8E92C9183RQHkaY',
    appId: '1:218095244490:android:930efef1d4b1054ac31033',
    messagingSenderId: '218095244490',
    projectId: 'recommendation-app-3c6d6',
    storageBucket: 'recommendation-app-3c6d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATRIVhZZzLVcPieUgtG1NfiDLi0iamMAs',
    appId: '1:218095244490:ios:6b45910bc14b1463c31033',
    messagingSenderId: '218095244490',
    projectId: 'recommendation-app-3c6d6',
    storageBucket: 'recommendation-app-3c6d6.firebasestorage.app',
    iosBundleId: 'com.example.recommendationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATRIVhZZzLVcPieUgtG1NfiDLi0iamMAs',
    appId: '1:218095244490:ios:6b45910bc14b1463c31033',
    messagingSenderId: '218095244490',
    projectId: 'recommendation-app-3c6d6',
    storageBucket: 'recommendation-app-3c6d6.firebasestorage.app',
    iosBundleId: 'com.example.recommendationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpxYa6MRQbmNY-Qai1TulAbZaTDNEY22Y',
    appId: '1:218095244490:web:63adc5f08ba57b76c31033',
    messagingSenderId: '218095244490',
    projectId: 'recommendation-app-3c6d6',
    authDomain: 'recommendation-app-3c6d6.firebaseapp.com',
    storageBucket: 'recommendation-app-3c6d6.firebasestorage.app',
    measurementId: 'G-RV3N78RL64',
  );
}
